### ISSUE TITLE
Add tests for a new network

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-terraform#33]
After network is created basic tests to check network status should be run (https://github.com/poanetwork/deployment-terraform/tree/master/helper-scripts/network-tests)

1. add a new option `run_tests: true/false` in terraform's `group_vars/all.yml` that determines if tests should be run or not after network is created
2. CI should set `run_tests: true`. CI should fail if tests fail
3. tests should be run from the local machine (it can be assumed that nodejs is installed locally - add this to documentation and in docker container)
4. tests require creating a local copy of `contracts/contracts.json` file from moc node, however another property should be added to that json file: `"POA_ADDRESS"` == address of safeContract from `spec.json`
5. in `config.toml` use moc's json keystore file and password, set `url` to `http://<balancer_ip>`

**Comment by ArseniiPetrovich** [comment]
During development we've found out, that it would be much more convenient to separate launch scripts for all the three workflow jobs (build, test, destroy) instead of creating boolean variables in `all.yml`. 
Also, we've assumed, that launching tests on MoC by default is a pretty good idea, but tests still could be easily launched anywhere where nodejs is installed.

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
